### ISSUE TITLE
Bad handling of multimodules releases

### ISSUE THREAD

**Issue by tmortagne** [schrepfler/jira-maven-plugin#11]
When releasing a project with several Maven modules, the release-jira-version defined in the parent pom is executed for every module which does not make much sense and slow the whole thing down a lot.

I looked at nexus plugin code and from what I understand they execute only if the current module is the last one. See https://github.com/sonatype/nexus-maven-plugins/blob/master/staging/maven-plugin/src/main/java/org/sonatype/nexus/maven/staging/AbstractStagingMojo.java#L329.

**Comment by tmortagne** [comment]
Actually maybe a cleaner way in recent Maven version is to implement a org.apache.maven.execution.ExecutionListener component to be called directly at the end of the session (sessionEnded()).

**Comment by schrepfler** [comment]
I would not declare it in a parent pom in build as then all children would inherit it in their lifecycle. You just need a single component which represents the product?

**Comment by tmortagne** [comment]
The thing is all the modules share the same jira project (which is quite standard, one repository=one jira project then you use modules in your jira project) so it makes sense to define what apply to the whole repository in the root pom. That's the same thing for Nexus repository example I mentioned.

The issue is that you don't exactly control which module is going to be executed last since Maven reorder then depending on dependencies, etc and you might add new modules for any reason so it's not really easy to just pick one and expect it to be the last one on the long run (unless you create some dummy module just for that not linked to the others but it's quite hacky).

**Comment by schrepfler** [comment]
It's also possible that submodules override the version from the parent and I would like to be able to support things like prefixing the version ID with a component label (because in JIRA you can't have versions per-component on a project.) Conceptually, I'm tempted to tread the parent pom's as abstract containers of concrete artefacts and JIRA-manage and version only the concrete ones. It's tempting even to say just create a fake sub module which will represent the module which will be mapped to JIRA.

**Comment by tmortagne** [comment]
Made it optional in my pull request.

**Comment by tmortagne** [comment]
Fixed by #12

**Comment by schrepfler** [comment]
Hi @tmortagne, I just released 0.5 to sonatype, give it a go and let me know if it's all OK?

**Comment by tmortagne** [comment]
I confirm it works perfectly :+1:
