### ISSUE TITLE
jira:generate-release-notes and duo security plugin

### ISSUE THREAD

**Issue by cliviu** [schrepfler/jira-maven-plugin#155]
Hi,
  When I try to run the plugin I get the following error. The credentials are ok but it looks like the output of the duo-security authentication is messing somehow with the plugin input : 
   
```
[ERROR] Error when executing mojo

Caused by: com.atlassian.jira.rest.client.api.RestClientException: org.codehaus.jettison.json.JSONException: A JSONObject text must begin with '{' at character 1 of <!DOCTYPE html>
<html>
  <head>
    <title>Duo Authentication</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body style="text-align: center;">
    <h1>Duo Authentication</h1>

     <div>
       <script type="text/javascript" src="/jira/download/resources/com.duosecurity.jira.plugins.duo-twofactor:resources/Duo-Web-v2.js"></script>
       <script>
         Duo.init({
           'host': "api-321af827.duosecurity.com",
           'sig_request': "",
           'post_action': ""});
       </script>
       <iframe id="duo_iframe" frameborder="0"></iframe>
       <style>
          #duo_iframe {
            width: 100%;
            min-width: 304px;
            max-width: 620px;
            height: 330px;
          }
        </style>
     </div>

  </body>
</html>
```

Do you have any hints for me  ? 

Thank you !

**Comment by dgrierso** [comment]
It sounds to me like your Jira service has [Duo for Jira Software](https://duo.com/docs/jira) installed and that it might not be fully configured properly.

From a quick scan of [this similar issue](https://github.com/duosecurity/duo_confluence/issues/3) it looks like you need to exempt particular URLs from Duo redirection in order for parts of them to work. In this case this would be your Jira server's REST API URI.

It's not directly related to the Jira-Maven plugin as the Jira service which I administrate uses SAML-SSO integrated with Azure and the plugin works with that - however what we have done is also included a token based authentication mechanism for access to the REST API.

**Comment by cliviu** [comment]
Hmm, strange, the [maven-changes-plugin](https://maven.apache.org/plugins/maven-changes-plugin/) has no problem generating reports because of the Duo-Jira Software. The problem with that we have with maven-changes-plugin is that the we cannot include custom fields as columns of the report. Does the jira-maven-plugin allow including custom fields in the report  ?

**Comment by cliviu** [comment]
does the plugin need a special version of Jira Server ?

**Comment by schrepfler** [comment]
> Hmm, strange, the [maven-changes-plugin](https://maven.apache.org/plugins/maven-changes-plugin/) has no problem generating reports because of the Duo-Jira Software. The problem with that we have with maven-changes-plugin is that the we cannot include custom fields as columns of the report. Does the jira-maven-plugin allow including custom fields in the report ?

@cliviu I'm closing this issue as you confirmed there's no problem with the Duo plugin. Would you like to champion adding support for including custom fields as columns in the report?
I can't answer the two questions as not working with JIRA actively at the moment so I don't have access to one, sorry.
