### ISSUE TITLE
Release a version with updated dependencies

### ISSUE THREAD

**Issue by jdtimmerman** [schrepfler/jira-maven-plugin#223]
This project was last released in 2020. In the meantime, there might not have been any functional changes, yet dependabot has not forgotten this project and kept the dependencies up to date. Including the JUnit version for which the current release has a known CVE security issue, as highlighted on the [mvnrepository.com page](https://mvnrepository.com/artifact/net.sigmalab.maven.plugins/jira-maven-plugin/0.9.2).

**Comment by schrepfler** [comment]
Hi @jdtimmerman, thank you for raising this issue, if nothing else to get me off my bum and clean up the project a bit. Versions have now been mostly updated (if available) and a new release is available.
