### ISSUE TITLE
NoClassDefFoundError: org/sonatype/plexus/components/sec/dispatcher/SecDispatcherException

### ISSUE THREAD

**Issue by tmortagne** [schrepfler/jira-maven-plugin#277]
I recently tried to upgrade to 0.9.6, but it seems to be missing some runtime dependency as it fail to lookup the CreateNewVersionMojo mojo because of

```
java.lang.NoClassDefFoundError: org/sonatype/plexus/components/sec/dispatcher/SecDispatcherException
```

It was with Maven 3.8.1.

**Comment by schrepfler** [comment]
Thanks for reporting this bug @tmortagne, I've noticed merging between dev/main was a bit hairy I hope this won't happen again. Can you give it a go now?

**Comment by tmortagne** [comment]
I don't reproduce the NoClassDefFoundError with 0.9.7. Did not actually try to create a new version, but at least I get "Version 14.5 already exists in jira.xwiki.org. Nothing to do." which is a good sign regarding the proper communication with the jira server API.

Thanks !
