### ISSUE TITLE
New jira-rest-java-client-core dependency breaks compatibility

### ISSUE THREAD

**Issue by schrepfler** [schrepfler/jira-maven-plugin#57]
Investigate why the branch #56 fails as it seems jira-rest-java-client has changed some packages and compatibility is affected.

**Comment by dgrierso** [comment]
Looks like 5.1.1 is not fully released yet. jira-rest-java-client-parent-5.1.1-e0dd194 is a pre-release version prior to them releasing 5.1.1

**Comment by schrepfler** [comment]
👍 Let's keep an eye on it, hopefully no major changes (though I hate their use of bespoke promises, Atlassian must have felt pretty courageous at the time).
If I was any younger I'd refactor all their promises code with CompletionStage and be done with it.
