### ISSUE TITLE
Migrate README.md to Wiki

### ISSUE THREAD

**Issue by dgrierso** [schrepfler/jira-maven-plugin#63]
We should make use of the [Wiki section](https://github.com/schrepfler/jira-maven-plugin/wiki) of the project area to document the plugin in a more structured and detailed manner.

This would hopefully assist users with finding information which might be buried at the bottom of a long README file.

**Comment by dgrierso** [comment]
Wiki has now been updated with content from the README.md and re-structured into appropriate pages.

**Comment by schrepfler** [comment]
🙌🙌🙌
